module.exports = {
    sock: null,
    store: null,
    reconnecting: false,
    reconnectTimer: null,
    reconnectAttempts: 0,
    qrToken: 0,
    qrUpdatedAt: 0,
    qrWatchdogTimer: null,
    scheduledMessagesTimer: null,
    startupTimeSec: Math.floor(Date.now() / 1000),
    totalMessagesHandled: 0,
    totalCommandsHandled: 0,
    sseClients: new Set(),
    chatHistories: new Map(),
    groupMessageBuffers: new Map(),
    seenMessageIds: new Set(),
    sentMessageIds: new Set(),
    spamTracker: new Map()
};
